{"uuid":"fa7698ef-0c4e-4ec9-a858-2c0a01caae91","name":"Scenario: User enters Invalid Python code and Presented with Error Message","children":["2781c49b-2626-46f2-8d9c-8125a001aa98"],"befores":[],"afters":[{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687733937685,"stop":1687733937686},{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687733937930,"stop":1687733937930},{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687733938078,"stop":1687733938078},{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687733938162,"stop":1687733938162},{"name":"hooks.AppHook.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1687733938181,"stop":1687733938181}],"start":1687733937536,"stop":1687733938181}